default_language_version:
  python: python3.13

repos:
  # Ruff: lint + format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # docformatter: docstrings
  - repo: https://github.com/pycqa/docformatter
    rev: 06907d0267368b49b9180eed423fae5697c1e909
    hooks:
      - id: docformatter
        args: [ -r, -i, --wrap-summaries=88, --wrap-descriptions=88, src, tests ]

  # bandit: security
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        exclude: ^tests/
        args: [ -r, src ]

  # pytest: test runner
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest tests --cov=src
        language: system
        types: [python]
        pass_filenames: false

  # pre-commit-hooks: additional checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
